# Generated by Django 3.2 on 2021-04-25 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohal', '0002_auto_20210425_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskBillDt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskDelDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskDispatchDt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskPoddt',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskcollectionDt',
            field=models.DateField(blank=True, null=True),
        ),
    ]
