# Generated by Django 3.2 on 2021-04-28 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohal', '0003_auto_20210425_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='taskBillNo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskChassisNo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskDealerName',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskDistance',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskDrivername',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskFrom',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskModelNo',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskStatus',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='task',
            name='taskTo',
            field=models.CharField(max_length=300),
        ),
    ]
