# Generated by Django 3.2 on 2021-05-03 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sohal', '0004_auto_20210428_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='taskCgst',
            field=models.FloatField(default=150),
            preserve_default=False,
        ),
    ]
