# Generated by Django 3.2 on 2021-05-04 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sohal', '0005_task_taskcgst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='taskCgst',
        ),
    ]
